### ISSUE TITLE
Error: Input required and not supplied [not a bug]

### ISSUE THREAD

**Issue by panosru** [ros-tooling/github-contribution-report-generator#190]
**this is not a bug report**

Hello, I can't figure out how to use this action, could you point me to the right direction?

This is the example workflow yaml file:

```yml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: ros-security/github-contribution-report-generator@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        since-n-days-ago: 7
        authors-filter: |
          thomas-moulard
        organizations-filter: |
          ros-security
```

Bug when I execute it I'm getting the following error:
![image](https://user-images.githubusercontent.com/400362/96375696-2a1f1480-1183-11eb-85c1-01d986b8983f.png)

I'm sure I'm doing something incorrectly but I'm not sure what exactly.

Thank you!
